UI block type examples
SkylineCommunications/dataminer-docs pull request #1012
Opened 2023-02-07 10:55 UTC by AaronVanVyve

Improved UIBlockTypes examples with functionality and explanations

2023-02-07 13:48 UTC, MariekeGO commented
Could you correct these unresolved cross-references?
![image](https://user-images.githubusercontent.com/94605575/217262323-7576a61e-aadb-46a4-9df4-eb04a0fc785f.png)

2023-02-13 12:46 UTC, Skyline-ThomasGH requested changes
These changed are a great improvement over the existing state of this page. There is still a lot of missing information, but this is a good step in the right direction. We should discuss whether it is worth the effort of providing a fully detailed doc page for this in an upcoming retro.

2023-02-13 12:46 UTC, Skyline-ThomasGH commented on develop/devguide/Automation/UIBlockTypesOverview.md
> +  Row = 1,
We could remove these row & column lines in all examples to safe some lines. These are generic fields that (should) behave the same for all blocks. The same could be said for the DestVar tbh, maybe only fill it in when the  block definition is accompanied by checking logic?

2023-02-13 13:02 UTC, Skyline-ThomasGH reviewed
Two additional notes.

2023-02-13 13:02 UTC, Skyline-ThomasGH commented on develop/devguide/Automation/UIBlockTypesOverview.md
> +  Type = UIBlockType.TreeView,
Maybe mention the 'using Skyline.DataMiner.Net.AutomationUI.Objects;' statement wich is required for the TreeViewItem.

2023-02-13 13:02 UTC, Skyline-ThomasGH commented on develop/devguide/Automation/UIBlockTypesOverview.md
> +var MyDialogBox = new UIBuilder() { Width = 800, RowDefs = "auto;auto", ColumnDefs = "auto;auto" };
Would change 'MyDialogBox' to 'uiBuilder' and make sure it is referenced everywhere like this. I found at least one (Numeric section) where something else is used.

2023-02-13 13:42 UTC, Skyline-ThomasGH approved these changes

2023-02-14 09:14 UTC, MariekeGO approved these changes

2023-02-14 09:15 UTC, merged