RN 35323
SkylineCommunications/dataminer-docs pull request #1146
Opened 2023-03-07 12:28 UTC by MariekeGO

2023-03-08 12:41 UTC, SDumoulein reviewed
I suggest to use 'rearrange' rather than 'reposition' as that's the wording which is used in the Cube UI as well. Also note that they can be rearranged, it's not something that always happens when using dynamic zooming.

2023-03-09 08:44 UTC, MariekeGO commented
> I suggest to use 'rearrange' rather than 'reposition' as that's the wording which is used in the Cube UI as well. Also note that they can be rearranged, it's not something that always happens when using dynamic zooming.

Updated! Could you take a look?

2023-03-14 12:28 UTC, SebastiaanSL requested changes

2023-03-14 12:28 UTC, SebastiaanSL commented on user-guide/Basic_Functionality/Visio/positioning_shapes/Enabling_dynamic_zoom_on_dynamically_positioned_shapes.md
> +From DataMiner 9.5.1 onwards, dynamic zooming can be configured when shapes are positioned dynamically. When dynamic zooming is enabled, shapes will not change in size when you zoom in, but will inst
This one should be kept as 'repositioned'.

2023-03-14 12:39 UTC, merged