Upgrading dma lvc
SkylineCommunications/dataminer-docs pull request #1188
Opened 2023-03-14 15:07 UTC by SLC-Laurens-Vercruysse

This pull request contains the updated upgrade paths and best practices page, as well as an updated VerifyNatsIsRunning prerequisite page. 
Note however, that the prerequisites for which Core Eco is not accountable have not yet been filled in. 
Likely we'll have to request feedback from the domains in question.

2023-03-16 14:46 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Preparing_to_upgrade_a_DataMiner_Agent.md
> +To make a backup of a DataMiner Agent using DataMiner Taskbar Utility or DataMiner Cube, see [Backing up a DataMiner Agent](xref:Backing_up_a_DataMiner_Agent).
For the sake of continuity, and if this is useful here, we could perhaps add a tip with more information on how to downgrade a DMS using a DataMiner backup as well? I am however unsure of whether to add a link to [Restoring a DataMiner Agent](https://docs.dataminer.services/user-guide/Advanced_Functionality/DataMiner_Agents/Restoring_a_DataMiner_Agent.html) or to [Downgrading a DMS](https://docs.dataminer.services/user-guide/Reference/MOPs/MOP_Downgrading_a_DMS.html).

2023-03-16 14:46 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Upgrade_Paths/Upgrade_path_960-96x_to_1030-103x.md
> +DataMiner 9.6.0/9.6.x -> DataMiner 10.0.0 [CU19] -> DataMiner 10.2.0/10.2.x
This upgrade path is identical to the one for DataMiner 9.6.0/9.6.x to DataMiner 10.2.0/10.2.x. 
Is it as simple as changing the last part?

```suggestion
DataMiner 9.6.0/9.6.x -> DataMiner 10.0.0 [CU19] -> DataMiner 10.3.0/10.3.x
```

2023-03-16 14:46 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Upgrade_Paths/Upgrade_path_960-96x_to_1020-102x.md
> +Never directly upgrade to a major DataMiner version that is several versions higher than the current version. To prevent issues and make it easier to find the root cause if anything goes wrong after
Is this still correct, seeing as you removed a similar sentence on the "Upgrading a DataMiner Agent" page?

2023-03-16 14:46 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Upgrade_Paths/Upgrade_path_960-96x_to_1030-103x.md
> +Never directly upgrade to a major DataMiner version that is several versions higher than the current version. To prevent issues and make it easier to find the root cause if anything goes wrong after
Same question: Change needed?
```suggestion
Follow this upgrade path:
```

2023-03-16 15:04 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Preparing_to_upgrade_a_DataMiner_Agent.md
> +To make a backup of a DataMiner Agent using DataMiner Taskbar Utility or DataMiner Cube, see [Backing up a DataMiner Agent](xref:Backing_up_a_DataMiner_Agent).
I've deleted all mentions to downgrading a DMS, as this was a misinterpretation on my part that could indeed be confusing and a no-go in the case of a DataMiner backup. See [commit](https://github.com/SkylineCommunications/dataminer-docs/pull/1188/commits/a339ad7ec18dde526354d2361490d41cfa2b0cc1).

2023-03-21 11:18 UTC, robin-devos-skyline requested changes
I updated this section based on DCP207984 
Also, there's a (hidden) comment in there with context + RN reference, not sure if it'll go noticed :)

2023-03-21 14:45 UTC, SLC-Laurens-Vercruysse reviewed
Changes looked good. Added comments below.

2023-03-21 14:45 UTC, SLC-Laurens-Vercruysse commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Upgrade_Paths/Upgrade_path_960-96x_to_1030-103x.md
> +  - [ASP.NET Core 6.0.13](https://download.visualstudio.microsoft.com/download/pr/0cb3c095-c4f4-4d55-929b-3b4888a7b5f1/4156664d6bfcb46b63916a8cd43f8305/dotnet-hosting-6.0.13-win.exe): If you want to
Correct suggestion. Should be updated as such.

2023-03-22 07:18 UTC, EdithLansens commented on user-guide/Advanced_Functionality/DataMiner_Agents/Upgrading_a_DMA/Preparing_to_upgrade_a_DataMiner_Agent.md
> +- Service Automatic Properties
I will contact Seppe to add a similar page dedicated to this prerequisite, ideally in the foreseeable future. Could you provide me with a short description of the prerequisite that I can put here in the meantime?

2023-03-23 08:43 UTC, merged