Add UIBlockType DownloadButton [RN35869] [DCP204668]
SkylineCommunications/dataminer-docs pull request #1252
Opened 2023-03-29 11:46 UTC by HansSolos

Doucmentation of new UIBlockType 'DownloadButton '.

2023-03-30 08:06 UTC, HansSolos reviewed
Update relative path examples.

2023-03-30 09:19 UTC, lander-vanhaverbeke-skyline requested changes
I suggest to change the wording a bit about the absolute/relative URL's.

2023-03-30 09:19 UTC, lander-vanhaverbeke-skyline commented on src/DataMiner/SLNetTypes/Automation/AutomationDownloadButtonOptions.cs
> +        /// When using an absolute URL, then it is recommended that the file is public accesible from the web.
I would remove the lines on line nrs 45 and 46. I think they only add confusion.

2023-03-30 09:36 UTC, lander-vanhaverbeke-skyline approved these changes

2023-03-30 10:04 UTC, lander-vanhaverbeke-skyline approved these changes

2023-03-30 10:04 UTC, HansSolos reviewed
Remove whitespace

2023-03-30 10:04 UTC, lander-vanhaverbeke-skyline approved these changes

2023-05-12 08:22 UTC, HansSolos reviewed
OK for me.
Asked Lander for optional look/opinion

2023-05-12 08:49 UTC, lander-vanhaverbeke-skyline approved these changes

2023-05-12 08:51 UTC, MariekeGO approved these changes

2023-05-12 08:51 UTC, merged