Overhaul databases
SkylineCommunications/dataminer-docs pull request #1427
Opened 2023-05-05 09:31 UTC by EdithLansens

2023-05-05 12:45 UTC, EdithLansens reviewed
This is a first version of the new Databases section, along with some questions/comments. As a lot of previously existing pages have been moved around, it is important to double-check that they have all been moved to a logical place. Several pages with new information have been added as well, which should be double-checked as well to see whether all added information is correct and whether no important information is missing.

2023-05-05 12:45 UTC, EdithLansens commented on user-guide/Advanced_Functionality/Databases/Configuring_dedicated_clustered_storage/Database_Configuration/Configuring_the_database_settings_in_Cube.md
> -## Legacy MySQL or SQL database
This has been moved to the new *Configuring the SQL database settings* page.

2023-05-05 12:45 UTC, EdithLansens commented on user-guide/toc.yml
> +                  topicUid: Configuring_Elasticsearch_indexing_database_backups
As of now, the *Configuring Elasticsearch indexing database backups* page is the only subpage under *Maintaining an indexing database*. Perhaps we could limit this to only one main page called *Configuring Elasticsearch indexing database backups* for now and return to this structure once more pages have been added.

2023-05-08 06:15 UTC, EdithLansens commented on user-guide/Advanced_Functionality/Databases/Databases_about.md
I will restructure/rewrite this *About* page, once we are completely happy with the Databases overhaul and new structure.

2023-05-08 06:17 UTC, EdithLansens commented on user-guide/Advanced_Functionality/Databases/Databases_about.md
>  - As a third alternative, soon it will be possible to use **Storage As A Service** on dataminer.services, so you no longer have to maintain the databases yourself, and all the scaling and complexity
Storage As A Service should become the main focus.

2023-06-06 14:05 UTC, SLC-Laurens-Vercruysse requested changes
Small change requested on the "multiple elastic" page. 
Since the "multiple elastic" setup merely offloads data to two separate databases without guarantee or syncing mechanism between those two databases, we try to not be promote it that much. For now, we can say something like "this should only be used when dealing with high latency. Low and medium latencies prefer a normal elasticsearch setup"
e.g. for Site redundancy, where the sites are located in different sites but still have reasonably good latency, other possibilities exist. Contact Skyline for more info on those.

2023-06-07 07:43 UTC, merged