Add workaround comment to IASToolkit examples
SkylineCommunications/dataminer-docs pull request #1443
Opened 2023-05-09 12:53 UTC by SkylineThomasCR

2023-05-09 12:54 UTC, SkylineThomasCR commented
Context: [https://community.dataminer.services/question/interactive-ui-can-only-be-used-in-interactive-mode-error-message-when-ias-toolkit/](https://community.dataminer.services/question/interactive-ui-can-only-be-used-in-interactive-mode-error-message-when-ias-toolkit/)

2023-05-10 09:57 UTC, MariekeGO requested changes

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // DO NOT REMOVE THIS COMMENTED OUT CODE OR THE SCRIPT WONT RUN!
```suggestion
        // DO NOT REMOVE THIS COMMENTED-OUT CODE OR THE SCRIPT WON'T RUN!
```

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // However, due to the toolkit nuget package, this string cannot be found here.
```suggestion
        // However, because of the toolkit NuGet package, this string cannot be found here.
```

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // DO NOT REMOVE THIS COMMENTED OUT CODE OR THE SCRIPT WONT RUN!
```suggestion
        // DO NOT REMOVE THIS COMMENTED-OUT CODE OR THE SCRIPT WON'T RUN!
```

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // However, due to the toolkit nuget package, this string cannot be found here.
```suggestion
        // However, because of the toolkit NuGet package, this string cannot be found here.
```

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // However, due to the toolkit nuget package, this string cannot be found here.
```suggestion
        // However, because of the toolkit NuGet package, this string cannot be found here.
```

2023-05-10 09:57 UTC, MariekeGO commented on develop/devguide/Automation/Howto/Getting_Started_with_the_IAS_Toolkit.md
> +        // DO NOT REMOVE THIS COMMENTED OUT CODE OR THE SCRIPT WONT RUN!
```suggestion
        // DO NOT REMOVE THIS COMMENTED-OUT CODE OR THE SCRIPT WON'T RUN!
```

2023-05-11 06:19 UTC, MariekeGO approved these changes

2023-05-11 06:19 UTC, merged