Update LogicQActions.md
SkylineCommunications/dataminer-docs pull request #1514
Opened 2023-05-23 14:58 UTC by DanielaOlive

improved clarity on Idisposable (works only when entry point method is non-static as well). Example: non-static QAction class with a static Run method does not work.

2023-05-24 09:57 UTC, PedroDebevere requested changes

2023-05-24 09:57 UTC, PedroDebevere commented on develop/devguide/Connector/LogicQActions.md
> +From DataMiner 10.2.9 onwards (RN 33965), DataMiner detects whether the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface is implemented on non-static QAction cl
```suggestion
From DataMiner 10.2.9 onwards (RN 33965), DataMiner detects whether the [IDisposable](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable) interface is implemented on non-static QAction classes with a non-static entry point method. DataMiner will then call the [Dispose](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) method when the QAction instance is released (i.e. when the element is stopped, removed, or restarted).

> [!NOTE]
> DataMiner will only create an instance of the class containting the entry point method if this method is not a static method (see [Instance entry methods](xref:LogicQActions#instance-entry-methods)). Therefore, if you want to make use of the IDisposable functionality, make sure that an instance gets created by having a non-static entry point method.
```

2023-06-06 12:39 UTC, MariekeGO approved these changes

2023-06-08 09:05 UTC, MariekeGO approved these changes

2023-06-08 09:05 UTC, merged