RN 36338
SkylineCommunications/dataminer-docs pull request #1545
Opened 2023-05-30 13:48 UTC by EdithLansens

Hi @VanRobaysWouter, could you take a look at this pull request to double-check whether I've correctly added RN 36338 to the user guide?

2023-05-31 05:51 UTC, VanRobaysWouter requested changes
Underneath the section that lists the options, there is an example of the default configuration, since the NatsSubject is now optional, this option should be removed from the default configuration example, this is on line 182

2023-05-31 06:10 UTC, EdithLansens commented on user-guide/Advanced_Modules/User Defined APIs/UD_APIs_UserDefinableApiEndpoint.md
> -    "NatsSubject": "Skyline.DataMiner.Protobuf.Apps.UserDefinableApis.Api.v1.UserDefinableApiTriggerRequest",
Is this OK, @VanRobaysWouter?

2023-05-31 06:17 UTC, VanRobaysWouter approved these changes
Looks good!

2023-06-01 08:55 UTC, MariekeGO approved these changes

2023-06-01 08:55 UTC, merged