SRM update
SkylineCommunications/dataminer-docs pull request #1570
Opened 2023-06-05 13:36 UTC by MariekeGO

Adds all the remaining info from the internal SRM user manual document except the Dijkstra topics.

2023-06-05 13:40 UTC, MariekeGO commented on user-guide/Standard_Apps/SRM/Booking_Manager/Booking_Manager_user_interface/Booking_Manager_Config_tab.md
At present there is no additional info anywhere on the option from line 101 (Include Contributing Service in Parent Service). Should we still add this somewhere?

2023-06-05 13:40 UTC, MariekeGO commented on user-guide/Standard_Apps/SRM/SRM_migrating/SRM_migrating_functions.md
> +1. Deploy the .dmapp package you want to import on the target DMS.
Can you deploy multiple packages and then run the script, or should you do this package by package?

2023-06-16 13:39 UTC, edalslc requested changes

2023-07-10 13:14 UTC, edalslc approved these changes

2023-07-10 13:26 UTC, merged