Update Cassandra_Cleaner.md
SkylineCommunications/dataminer-docs pull request #1674
Opened 2023-06-26 12:06 UTC by KevinVerm

2023-06-26 12:26 UTC, MariekeGO requested changes

2023-06-26 12:26 UTC, MariekeGO commented on user-guide/Reference/DataMiner_Tools/Cassandra_Cleaner.md
> +### db.yaml
What about settings.yaml? If all the information below is exclusively related to db.yaml, how should users configure settings.yaml?

2023-06-27 06:41 UTC, KevinVerm commented on user-guide/Reference/DataMiner_Tools/Cassandra_Cleaner.md
> +Depending on the *db.yaml* configuration, the arguments provided to clean the table are configured as mentioned below when running the executable:
Done

2023-06-28 10:49 UTC, MariekeGO approved these changes

2023-06-28 10:49 UTC, merged