[STaaS] Error for API Deployment
SkylineCommunications/dataminer-docs pull request #2097
Opened 2023-10-11 07:34 UTC by GuillaumeVadeBe

Added the error that will be shown when API Deployment is still enabled in the SoftLaunchOptions while it shouldn't be.

2023-10-11 07:36 UTC, LouisSkyline approved these changes

2023-10-11 07:39 UTC, LouisSkyline requested changes
Also mention the error shown in cube, as this is the one users will see most likely first

2023-10-13 06:47 UTC, joaobarraca approved these changes

2023-10-13 08:09 UTC, MariekeGO approved these changes

2023-10-13 08:09 UTC, merged