Create DIS_2.45.md
SkylineCommunications/dataminer-docs pull request #2127
Opened 2023-10-16 11:06 UTC by PedroDebevere

2023-10-16 11:18 UTC, MichielOda requested changes

2023-10-16 11:18 UTC, MichielOda commented on release-notes/DIS/DIS_2.45.md
> +
```suggestion
- Skyline.DataMiner.CICD.CSharpAnalysis.Common
- Skyline.DataMiner.CICD.CSharpAnalysis.Protocol

- Skyline.DataMiner.CICD.Models.Common

```

2023-10-16 11:18 UTC, MichielOda commented on release-notes/DIS/DIS_2.45.md
> +The driver help generation in DIS has been updated so that it now generates a markdown file (.md) to be used in the docs repository instead of an HTML page that was used on DCP. The menu item that al
Menu item isn't actually renamed.

2023-10-16 11:18 UTC, MichielOda commented on release-notes/DIS/DIS_2.45.md
> +TThe SLDisCompiler project has been extracted from DIS and the functionality from this project has been migrated to the already existing NuGet package "Skyline.DataMiner.CICD.Parsers.Protocol" and th
```suggestion
The SLDisCompiler project has been extracted from DIS and the functionality from this project has been migrated to the already existing NuGet package "Skyline.DataMiner.CICD.Parsers.Protocol" and the newly introduced NuGet package "Skyline.DataMiner.CICD.Assemblers.Protocol".
```

2023-10-16 11:33 UTC, PedroDebevere commented on release-notes/DIS/DIS_2.45.md
> +The driver help generation in DIS has been updated so that it now generates a markdown file (.md) to be used in the docs repository instead of an HTML page that was used on DCP. The menu item that al
updated

2023-10-17 06:32 UTC, MichielOda approved these changes

2023-10-17 10:42 UTC, spetebroodt approved these changes

2023-10-17 10:43 UTC, spetebroodt commented
@MichielOda @PedroDebevere Can you double-check my corrections before I merge this?

2023-10-17 14:20 UTC, MichielOda commented
> @MichielOda @PedroDebevere Can you double-check my corrections before I merge this?

Looks good to me. Once Pedro confirms, then this can be merged.

2023-10-18 06:06 UTC, PedroDebevere commented
updates are ok

2023-10-18 06:11 UTC, merged