Cube features 10.2.6
SkylineCommunications/dataminer-docs pull request #216
Opened 2022-05-04 11:52 UTC by MariekeGO

2022-05-10 08:45 UTC, bertbsky requested changes

2022-05-10 08:45 UTC, bertbsky commented on user-guide/Getting_started/Accessing_DataMiner/Accessing_DataMiner_Cube/Opening_DataMiner_Cube.md
> +- [bypassProxy=true](#bypassproxytrue)
The `bypassProxy` argument is not an option for Cube, it is interpreted by the IIS `dataminer-failover-reverseproxy-rule` rewrite rule. It is not intended to be used directly by end-users and as such I would exclude it from documentation.

2022-05-10 08:45 UTC, bertbsky commented on user-guide/Getting_started/Accessing_DataMiner/Accessing_DataMiner_Cube/Opening_DataMiner_Cube.md
> +
Same as line 193, I would exclude this from documentation.

2022-05-10 08:45 UTC, bertbsky commented on user-guide/Advanced_Functionality/DataMiner_Agents/Configuring_a_DMA/DMA_configuration_related_to_client_applications.md
> +> - By default, this is configured for the entire DMS. If you select the checkbox *Allow individual agent configuration*, you can configure different client version settings per DMA instead. However,
I would further clarify why it is not recommended:
> * ...  However, this is not recommended as users will end up using a different version of Cube depending on which agent they connect to.

An important additional note to make here:
> * When adding a new agent to a cluster, that new agent will come with the default configuration (*Allow automatic updates*) so keep this in mind and apply the same forced version on it after joining the cluster.

This user experience is not ideal and will be further improved upon with DCP184996.

2022-05-10 08:45 UTC, bertbsky commented on user-guide/Getting_started/Accessing_DataMiner/Accessing_DataMiner_Cube/Opening_DataMiner_Cube.md
> +   - **Preview**: Use a preview of the latest DataMiner Cube version, even if it has not been released yet.
Note: the _development_ and _preview_ tracks are only available to Skyline employees.

2022-05-11 07:14 UTC, bertbsky commented on user-guide/Advanced_Functionality/DataMiner_Agents/Configuring_a_DMA/DMA_configuration_related_to_client_applications.md
> +   - **Force a specific version**: This will force users to always use a particular Cube version, which you will need to select on the server when you choose this option.
More specifically, a file dialog will appear where the user needs to provide two files: Cube.zip and versions.txt. These files can be obtained from the /Webpages/DataMinerCubeStandAlone/ folder in an upgrade package or on another DataMiner agent (e.g. staging platform).
This user experience will be further improved upon with DCP182390.

2022-05-16 11:12 UTC, MariekeGO commented
@bertbsky I've made the necessary changes based on your feedback. Could you check if everything is now OK to merge?

2022-05-18 07:14 UTC, bertbsky approved these changes

2022-05-18 07:16 UTC, merged