VerifyNoObsoleteApiDeployed prerequisite
SkylineCommunications/dataminer-docs pull request #2233
Opened 2023-11-07 11:09 UTC by VanRobaysWouter

DCP223461

2023-11-07 11:49 UTC, Skyline-ThomasGH requested changes

2023-11-07 11:49 UTC, Skyline-ThomasGH commented on user-guide/Troubleshooting/Known_issues/KI_Upgrade_fails_VerifyNoObsoleteAPIDeployed_prerequisite.md
> +1. Your API's will be displayed in a tree view
```suggestion
1. Your APIs will be displayed in a tree view
```

2023-11-07 11:49 UTC, Skyline-ThomasGH commented on user-guide/Troubleshooting/Known_issues/KI_Upgrade_fails_VerifyNoObsoleteAPIDeployed_prerequisite.md
> +1. Your API's will be displayed in a tree view
Also indent this since this is not action but a result of what you will see after the previous action.

2023-11-07 11:49 UTC, Skyline-ThomasGH commented on user-guide/Troubleshooting/Known_issues/KI_Upgrade_fails_VerifyNoObsoleteAPIDeployed_prerequisite.md
> +1. When finished, you should only have *Unused Tokens* left in your treeview. This process only needs to be done on one system in the cluster, changes will be synced to the entire cluster.
This gives additional info on the procedure and is not an action, so it should not be part of the 'steps' list.

2023-11-07 11:49 UTC, Skyline-ThomasGH commented on user-guide/Troubleshooting/Known_issues/KI_Upgrade_fails_VerifyNoObsoleteAPIDeployed_prerequisite.md
> +---
Probably best to go over these tips: https://docs.dataminer.services/CONTRIBUTING.html#tips-for-writing-documentation. There are some things here that should be avoided according to those (avoid contractions).

2023-11-07 12:31 UTC, Skyline-ThomasGH approved these changes

2023-11-07 12:31 UTC, Skyline-ThomasGH commented on user-guide/Troubleshooting/Known_issues/KI_Upgrade_fails_VerifyNoObsoleteAPIDeployed_prerequisite.md
> +If you don't want to lose your APIs, you will have to migrate them to use the new User-Defined APIs feature. There is documentation on how to [define a new API](xref:UD_APIs_Define_New_API) and how t
```suggestion
If you do not want to lose your APIs, you will have to migrate them to use the new User-Defined APIs feature. There is documentation on how to [define a new API](xref:UD_APIs_Define_New_API) and how to [create an API from an existing automation script](xref:UD_APIs_Using_existing_scripts).
```

2023-11-07 14:05 UTC, edalslc approved these changes

2023-11-09 08:30 UTC, spetebroodt approved these changes

2023-11-09 08:37 UTC, merged