Grid component
SkylineCommunications/dataminer-docs pull request #2291
Opened 2023-11-17 13:51 UTC by EdithLansens

New visualization available for DataMiner Dashboards and Low-Code Apps: the grid component.

Currently only available if ReportsAndDashboardsDynamicVisuals soft-launch option is enabled.

RNs: 34761, 34781, 34948, 37269, and 37699.

2023-11-20 08:26 UTC, EdithLansens commented
Hi @GillesBara, @simonmestdagh2, @WaHaeck, and @SebastiaanSL, could you review this pull request to ensure the accurate inclusion of the grid component in the user guide? More information is set to follow about the Template Editor in an upcoming pull request.

2023-11-21 10:31 UTC, GillesBara requested changes

2023-11-21 10:31 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Grid.md
> +1. Optionally, hover the mouse over the component, click the filter icon, and then add a filter feed from the *queries* section of the data pane. You can repeat this several times in order to filter
The only filter that currently makes sense to the grid is the columns from the query filter component, which will be available under Feeds > Query filter >Query Columns

2023-11-21 10:31 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Grid.md
> +> At present, this component is only available in preview, if the [ReportsAndDashboardsDynamicVisuals](xref:Overview_of_Soft_Launch_Options#reportsanddashboardsdynamicvisuals) soft-launch option is e
The component is available without softlaunch from 10.4.1. Between 10.2.12 and 10.4.1 it's available with the softlaunch. This note makes me think I can only use the component with the flag enabled from 10.4.1 onwards.

2023-11-21 10:31 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Grid.md
> +   - *Item templates > Alarms*: Allows you to freely customize the appearance of the grid component using templates<!--RN 34761-->.
This "Alarms" is the name of the query, not a fixed part of the setting name

2023-11-22 15:21 UTC, EdithLansens commented
Hi @GillesBara, thanks for the feedback! I've made the associated changes in [commit 7704d11](https://github.com/SkylineCommunications/dataminer-docs/pull/2291/commits/7704d11b1cd1cfeaa62ad4d8684f1072c18700e5).

2023-11-23 08:20 UTC, GillesBara approved these changes

2023-11-23 09:58 UTC, MariekeGO approved these changes

2023-11-23 09:58 UTC, merged