Backup procedure for Cassandra cluster using Medusa
SkylineCommunications/dataminer-docs pull request #2294
Opened 2023-11-20 09:40 UTC by meitavelo

How to configure Medusa, how to take a backup and how to restore a backup.

2023-11-20 09:40 UTC, meitavelo commented
@ThibaultHeylen

2023-11-27 14:27 UTC, MariekeGO requested changes
Could you go over your procedure again and add more detail? Right now, many of the steps are too vague for users to easily be able to follow. For instance, for line 14/18: where should the user specify that command? Is this the same regardless of which OS they are using or does your procedure apply for a specific OS? For line 16: where do they find the public key and where do they paste it? Make sure there is no missing info in the procedure and that it's always clear what the users need to do and where.
Note also that I've now moved the "Generate SSH keys" section to the top because I get the impression they can't do the backup unless this has been done, but perhaps it might be better to actually combine the backup procedure with the procedure to generate SSH keys, as one continuous set of steps?

2023-12-15 12:34 UTC, spetebroodt commented
Hi @meitavelo Can you double-check the corrected text? Also, two different Linux flavors are mentioned on this page: Ubuntu LTS and CentOS (link to procedure specific for CentOS?). Is this correct? I thought Ubuntu LTS is recommended.

2023-12-19 14:55 UTC, spetebroodt approved these changes

2023-12-19 14:57 UTC, merged