Timeline component
SkylineCommunications/dataminer-docs pull request #2368
Opened 2023-12-05 12:42 UTC by EdithLansens

From DataMiner 10.4.1/10.5.0 onwards, the timeline component is available out of soft launch. Prior to this (from DataMiner 10.1.10 onwards), this component is available if the *ReportsAndDashboardsScheduler* soft-launch option is enabled.

Release notes included in this pull request:

@GillesBara: RN 35639 + 35620 + 33311 (to be added: RN 33694)
@WoutMH: RN 33639 (to be added: RN 33657)
@Robin-Debel: RN 35619
@simonmestdagh2: (to be added: RN 35638 + 35600)
@WaHaeck: RN 33287
@skyline-rge: RN 33276

Could you verify whether your respective release note(s) were documented accurately?

Four release notes have yet to be added: RN 33694 + 33657 + 35638 + 35600

Could you review this pull request to ensure the accurate inclusion of the timeline component in the user guide, @GillesBara, @Robin-Debel, and @SebastiaanSL?

2023-12-05 13:32 UTC, GillesBara requested changes

2023-12-05 13:32 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Timeline_component.md
> +     To use the default time range configured for another component in the dashboard or low-code app, click the ![Link to feed](~/user-guide/images/Link_to_Feed.png) icon next to *Link time range to
The "link to feed" has nothing to do with the default time range. When you link the timeline to eg a time range component, the timeline will show the range that is selected by that linked time range component. When you would for example switch the timerange in the timerange component to "this week", the timeline will immediatly also switch to this week.

2023-12-05 13:32 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Timeline_component.md
> +   - *Highlight range > Use highlighting*: Determines whether an event in the timeline component is highlighted when it falls within the configured time range. When an event is highlighted, it receiv
The blue is defined by the color palette of the dashboard theme.

2023-12-05 13:32 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Timeline_component.md
> +       > When you disable the *Highlight* option, the nodes that do not match the filter will no longer be displayed and the remaining nodes will be reorganized.
*Nodes* is from the node-edge, this setting is indeed the same one as with the node-edge, but I wouldn't call it nodes in this context.

2023-12-05 13:32 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Timeline_component.md
> +     - *Lock timeline to now*: Determines whether users are allowed to navigate past the current timestamp in read mode. Disabled by default.
The locking is not really blocking user from going past the current timestamp, but more keeping the now indicator on a fixed position. They can zoom in and out, but not pan. The now pointer will remain on the fix position and the timeline itself will pan automatically in time. (zoom in a lot to see the clearly)

2023-12-05 13:32 UTC, GillesBara commented on user-guide/Advanced_Modules/Dashboards_and_Low_Code_Apps/Visualizations/Available_visualizations/Other/Timeline_component.md
> +In read mode, you can manipulate the timeline component to navigate through the scheduled events, bookings, or time-bound data .
whitespace before period at the end

2023-12-06 12:17 UTC, EdithLansens commented
Hi @GillesBara, thanks for the input! I have implemented your feedback in commit [4957541](https://github.com/SkylineCommunications/dataminer-docs/pull/2368/commits/4957541710c53c54695f6c122bab8f61557227c9).

2023-12-06 15:03 UTC, EdithLansens commented
Hi @WoutMH, thank you for going over the pull request! I have implemented your feedback in commit [d0229b3](https://github.com/SkylineCommunications/dataminer-docs/pull/2368/commits/d0229b3f701f78e018f29e788a3a6119451b8449).

2023-12-07 07:23 UTC, Robin-Debel approved these changes

2023-12-07 10:36 UTC, merged