DCP218827_AddedDocsForGetDifferences_DOM
SkylineCommunications/dataminer-docs pull request #2576
Opened 2024-01-22 11:08 UTC by AaronVanVyve

2024-01-23 11:05 UTC, VanRobaysWouter commented on user-guide/Advanced_Modules/DOM/DOM_examples/DOM_GetDifferences.md
> +These methods can be chained to create the specific conditions to get your desired differences.
```suggestion
These methods can be chained to create specific conditions to get your desired differences.
```

2024-01-23 11:07 UTC, VanRobaysWouter commented on user-guide/Advanced_Modules/DOM/DOM_examples/DOM_GetDifferences.md
> +These FieldValueDifferences contain a list of FieldValueDifference:
```suggestion
This `FieldValueDifferences` object contains a list of `FieldValueDifference` objects:
```

2024-01-23 11:07 UTC, VanRobaysWouter commented on user-guide/Advanced_Modules/DOM/DOM_examples/DOM_GetDifferences.md
> +|Type | CrudType | The CrudType of the changed FieldDescriptor (Create, Update & Delete) |
```suggestion
|Type | CrudType | The CrudType of the changed FieldDescriptor (Create, Update or Delete) |
```

2024-01-23 11:08 UTC, VanRobaysWouter commented on user-guide/Advanced_Modules/DOM/DOM_examples/DOM_GetDifferences.md
> +|FieldDescriptorId | FieldDescriptorID | The ID the changed FieldDescriptor|
```suggestion
|FieldDescriptorId | FieldDescriptorID | The ID of the changed FieldDescriptor|
```

2024-01-24 13:56 UTC, Ghysbrecht requested changes

2024-01-29 13:07 UTC, Skyline-ThomasGH requested changes

2024-01-30 11:04 UTC, Skyline-ThomasGH approved these changes

2024-02-02 07:37 UTC, MariekeGO commented on user-guide/Advanced_Modules/DOM/DOM_ModuleSettings/ExecuteScriptOnDomInstanceActionSettings.md
> +These methods can be chained to create specific conditions to get your desired differences. In most situations the `Get()` method should be applied in the end, to get a list of `FieldValueDifference`
```suggestion
These methods can be chained to create specific conditions to get your desired differences. In most situations, the `Get()` method should be applied at the end, to get a list of `FieldValueDifference` objects and use the properties it contains.
```

2024-02-19 07:25 UTC, merged