Dataminer services status
SkylineCommunications/dataminer-docs pull request #2722
Opened 2024-02-15 13:23 UTC by baptistepa

Added description of the new status indicators for the connections between the DMS and the dataminer.services platform.

2024-02-15 14:02 UTC, AlexanderVK-SLC requested changes

2024-02-15 14:02 UTC, AlexanderVK-SLC commented on user-guide/Cloud_Platform/AboutCloudPlatform/About_the_Cloud_Platform.md
> +Everything is okay and you can access your system and use all the features that the dataminer.services platform offers. This is indicated by the green colored icon icon and the green bar next to the
```suggestion
Everything is okay and you can access your system and use all the features that the dataminer.services platform offers. This is indicated by the green colored icon and the green bar next to the DMS information.
```

2024-02-15 14:02 UTC, AlexanderVK-SLC commented on user-guide/Cloud_Platform/AboutCloudPlatform/About_the_Cloud_Platform.md
> +Your DMS has a connection to dataminer.services but the DMS itself is not running. This is indicated by the orange colored icon and the orange color next to the DMS information. When hovering over th
Don't think we need to add this, as we can update the title at some point and will probably forget to update these docs for such a 'small' change

2024-02-15 14:02 UTC, AlexanderVK-SLC commented on user-guide/Cloud_Platform/AboutCloudPlatform/About_the_Cloud_Platform.md
> +We can't determine the status of the connection because of an error in dataminer.services. In this case you will get a warnining.
```suggestion
We can't determine the status of the connection because of an error in dataminer.services. In this case you will get a warning.
```

2024-02-15 15:11 UTC, AlexanderVK-SLC approved these changes

2024-02-19 10:57 UTC, MariekeGO commented
@baptistepa, I've reviewed your PR and made some changes. Could you take a look and let me know if everything is still OK for you?

2024-02-20 13:50 UTC, baptistepa reviewed
Looks good to me.

2024-02-20 14:13 UTC, MariekeGO approved these changes

2024-02-20 14:13 UTC, merged