Ping monitor update
SkylineCommunications/dataminer-docs pull request #3385
Opened 2024-07-02 13:25 UTC by spetebroodt

2024-07-05 07:50 UTC, EdithLansens approved these changes

2024-07-08 19:03 UTC, migbarq commented on user-guide/Standard_Apps/Monitoring_Solutions/Ping_Monitoring/Ping_Monitoring_UI.md
> +- **Ping result**: The time it took for the server to reply to the last ping command, e.g. *4 ms*.
The time it took each destination to reply [...]

2024-07-08 19:04 UTC, migbarq commented on user-guide/Standard_Apps/Monitoring_Solutions/Ping_Monitoring/Ping_Monitoring_UI.md
> +In the lower-left corner, you can see the total destinations as well as the destinations that are currently active in your DataMiner System. Also, a progress bar above those destinations will count d
Also, a progress bar above those destinations will count down to the next page refresh.

2024-07-08 19:05 UTC, migbarq requested changes
I left a few comments with the changes I consider necessary. Everything else looks good. Thanks

2024-07-09 09:55 UTC, merged