Admin Usage page information
SkylineCommunications/dataminer-docs pull request #3450
Opened 2024-07-12 09:29 UTC by julienVerm

2024-07-15 11:53 UTC, ruben12321 requested changes

2024-07-15 11:53 UTC, ruben12321 commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +Currently the only feature that reports usage data is Storage as a Service (STaaS), which reports amount of ingest operations per data type, but the list of 'features' will grow in the future. For mo
```suggestion
Currently the only feature that reports usage data is Storage as a Service (STaaS), which reports amount of ingest operations per data type. The list of 'features' will grow in the future. For more information about the metering and conversion rates, see this [Page].(https://docs.dataminer.services/dataminer-overview/Pricing/Pricing_Usage_based_service.html#metering-units)
```

2024-07-15 11:53 UTC, ruben12321 commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +It is possible to filter on months although you do not have anything consumed during that period. By selecting one or multiple DataMiner systems you can view the usage for selected systems.
```suggestion
It is possible to filter on months even if you have not consumed anything during that period. By selecting one or multiple DataMiner systems you can view the usage for selected systems.
```

2024-07-15 11:53 UTC, ruben12321 commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +> - Organization with no DataMiner systems that use any of the supported 'features' will see an error message stating that there is no data found for this organization.
```suggestion
> - An organization with no DataMiner systems that use any of the supported 'features' will see an error message stating that there is no data found for this organization.
```

2024-07-15 12:08 UTC, AlexanderVK-SLC commented
Add the new file to the toc

2024-07-15 12:15 UTC, AlexanderVK-SLC requested changes
Did you run this locally to see what it looks like? I think your URL was broken too as it is right now

2024-07-15 12:15 UTC, AlexanderVK-SLC commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +Currently the only feature that reports usage data is Storage as a Service (STaaS), which reports amount of ingest operations per data type, but the list of 'features' will grow in the future. For mo
```suggestion
Currently the only feature that reports usage data is Storage as a Service (STaaS), which reports amount of ingest operations per data type, but the list of 'features' will grow in the future. For more information about the metering and conversion rates, see this [Usage-based services: Metering](https://docs.dataminer.services/dataminer-overview/Pricing/Pricing_Usage_based_service.html#metering-units).
```

2024-07-15 12:15 UTC, AlexanderVK-SLC commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +In the Admin app, you can view information about the usage of certain 'features' in a DataMiner System. Usage is reported in DataMiner credits.
```suggestion
In the Admin app, you can view information about the usage of certain features in a DataMiner System. Usage is reported in DataMiner credits.
```

2024-07-15 12:21 UTC, MariekeGO commented on user-guide/Cloud_Platform/CloudAdminApp/Viewing_info_on_system_usage.md
> +Currently the only feature that reports usage data is Storage as a Service (STaaS), which reports amount of ingest operations per data type, but the list of 'features' will grow in the future. For mo
Links to other pages within the same repo should be done by UID to make sure that they're update-proof. If you link to the URL, and the link no longer works, you won't get a warning. In this case, this link should be configured as `[Metering](xref:Pricing_Usage_based_service#metering-units)`. For detailed info, see [Links and cross-references](https://docs.dataminer.services/contributing/CTB_Markdown_Syntax.html#links-and-cross-references).

2024-07-16 06:41 UTC, MariekeGO approved these changes

2024-07-16 06:41 UTC, merged