Remote cube limited access based on IP
SkylineCommunications/dataminer-docs pull request #3486
Opened 2024-07-19 11:23 UTC by JordyGit

2024-07-19 12:45 UTC, JordyGit commented
TODO: Add more info in the docs: https://docs.dataminer.services/user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.html?q=organization%20setting

2024-07-23 11:11 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
> +The dataminer.services settings, configurable from the Admin app, have been enhanced so you can limit remote access to Cube for each specific DMS based on (public) IP address.
```suggestion
The dataminer.services settings, configurable from the Admin app, have been enhanced so you can restrict remote access to Cube for each specific DMS based on (public) IP address.
```

2024-07-23 13:13 UTC, EdithLansens commented
> TODO: Add more info in the docs: https://docs.dataminer.services/user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.html?q=organization%20setting

This information has now been added to this pull request.

Note: Once the text in the Admin app is finalized, some changes will need to be made to the documentation to accurately represent the UI.

2024-07-23 15:45 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +   - *Remote Cube allowed IPs*: Only available if the *DataMiner Cube (desktop app)* setting is enabled. This setting allows you to restrict access to the DMS based on specified IP addresses.
```suggestion
   - *Restict by IP address*: Only available if the *DataMiner Cube (desktop app)* setting is enabled. This setting allows you to restrict remote access to the DMS via the desktop app based on the specified client public IP addresses.
   > [!NOTE]
   > Only public IP addresses can be specified
```

2024-07-23 15:46 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +   - *Remote Cube allowed IPs*: Only available if the *DataMiner Cube (desktop app)* setting is enabled. This setting allows you to restrict access to the DMS based on specified IP addresses.
ideally add a tab to indicate this is a sub setting of "DataMiner Cube (desktop app)"

2024-07-23 15:48 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +     ![Managing IP addresses](~/user-guide/images/Managing_IP_Addresses.png)
Cut the image to the popup? because the setting name on the left is outdated already and new settings will be added in the future either

2024-07-24 06:39 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +     > Only public IP addresses can be added to the list of trusted IP addresses.
```suggestion
     > Only public IP addresses can be added to the list of allowed IP addresses.
``` (in sync with the ui?)

2024-07-25 08:48 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
> +#### 24 July 2024 - Enhancement - New remote access setting to restrict remote Cube access based on IP addresses [ID_]
```suggestion
#### 24 July 2024 - Enhancement - New remote access setting to restrict remote Cube access based on IP addresses [ID_40288]
```

2024-07-25 08:48 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +     - *Restrict by IP address*<!--RN number will be added here-->: Only available if the *DataMiner Cube (desktop app)* setting is enabled. This setting allows you to restrict remote access to the D
```suggestion
     - *Restrict by IP address*<!--RN 40288-->: Only available if the *DataMiner Cube (desktop app)* setting is enabled. This setting allows you to restrict remote access to the DMS via the desktop app based on the specified client public IP addresses.
```

2024-07-25 11:27 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
> +An enhancement has been made to the remote access settings in the Admin app, which allows you to restrict remote Cube access based on specified public IP addresses.
```suggestion
An enhancement has been made to the remote access settings in the Admin app, which allows you to restrict remote Cube access per DMS based on specified public IP addresses.
```

2024-07-25 11:29 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
> +An enhancement has been made to the remote access settings in the Admin app, which allows you to restrict remote Cube access based on specified public IP addresses.
or at the end?
```suggestion
An enhancement has been made to the remote access settings in the Admin app, which allows you to restrict remote Cube access based on specified public IP addresses per DMS.
```

2024-08-01 10:01 UTC, julienVerm requested changes

2024-08-01 10:01 UTC, julienVerm commented on release-notes/Cloud/DCP_change_log.md
```suggestion

#### 1 August 2024 - Fix - Admin - Formatting of numbers under a thousand having a K suffix [ID 40383]

Smaller numbers will no longer be formatted with suffixes to improve readability. Previously, navigating to the usage page in Admin you could find numbers under the operation column to be formatted with the K suffix which would result in 0.x K formatting.

```

2024-08-01 10:03 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
> +#### 1 August 2024 - Fix - Admin - Formatting of numbers under a thousand having a K suffix [ID 40383]
to be checked by tw

2024-08-01 12:28 UTC, JordyGit commented on release-notes/Cloud/DCP_change_log.md
```suggestion

#### 1 August 2024 - Enhancement - Catalog - Renamed contributors section to owners [ID_40378]

All references to contributors have been renamed owners on the catalog details page

#### 1 August 2024 - Fix - Catalog - Filters are not restored on browse page opening browse page [ID_40332]

When users start from the browse page and set some filters these will now be restored if they come back from a details page; before all the filters would be reset.

#### 1 August 2024 - Fix - Cloud apps - Unsuported page is never shown [ID_40347]

When a user is using an old browser (e.g. IE) a white page would be displayed due to the JS not loading in correctly.
This has been resolved so the user now sees that his/her browser is no longer supported and should use a newer one.

```

2024-08-01 13:45 UTC, merged