Add docs on ResourceManagerHelper
SkylineCommunications/dataminer-docs pull request #3712
Opened 2024-09-19 06:58 UTC by Seppe-Vanhee

2024-09-20 11:29 UTC, VanRobaysWouter approved these changes

2024-09-20 14:06 UTC, slc-peter-vanpoucke requested changes

2024-09-20 14:06 UTC, slc-peter-vanpoucke commented on user-guide/Standard_Apps/SRM/Interacting_with_SRM_using_code/srm_using_resourcemanagerhelper.md
> +| InitializeFunctionResourceFailed | Occurs when a FunctionResource could not be initialized. | *SubjectId* contains the ID of the ``Resource`` that failed to initialize.<br>*InitializeFunctionResour
S: ``FunctionResource``

2024-09-20 14:07 UTC, Skyline-ThomasGH requested changes
Tested the code blocks which revealed some small errors. I had to include some namespaces, that to me were obvious, but there are sometimes two namespaces that contain the same class (the correct and the proto generator one). Not sure if we should clarify this more.

2024-09-20 14:07 UTC, Skyline-ThomasGH commented on user-guide/Standard_Apps/SRM/Interacting_with_SRM_using_code/srm_using_resourcemanagerhelper.md
> +var oldProperties = reservationInstance.Properties; // The current properties on the booking we intent to overwrite
```suggestion
var oldProperties = reservationInstance.Properties; // The current properties on the booking we intend to overwrite
```

2024-09-23 09:58 UTC, Seppe-Vanhee commented on user-guide/Standard_Apps/SRM/Interacting_with_SRM_using_code/srm_using_resourcemanagerhelper.md
> +    TimeRange = new TimeRangeUtc(now.AddHours(1), now.AddHours(4)),
Added a comment in each code snippet if a specific namespace is needed. I think it's easier to clarify which namespaces are required for which code that way.

2024-09-23 10:06 UTC, Skyline-ThomasGH approved these changes

2024-09-23 13:54 UTC, slc-peter-vanpoucke commented on user-guide/Standard_Apps/SRM/Interacting_with_SRM_using_code/srm_using_resourcemanagerhelper.md
> +> On a DataMiner Agent that is using OpenSearch or Elasticsearch, there is a default limit of 1024 clauses in a query. This means that you can only concatenate a maximum of 1024 filters using an "OR"
@Skyline-ThomasGH what is your opinion?

2024-09-23 16:16 UTC, slc-peter-vanpoucke requested changes

2024-09-24 08:20 UTC, slc-peter-vanpoucke commented
ok

2024-09-24 08:20 UTC, slc-peter-vanpoucke approved these changes

2024-09-25 11:29 UTC, MariekeGO approved these changes

2024-09-25 11:29 UTC, merged