Add new error to DomInstancError
SkylineCommunications/dataminer-docs pull request #3747
Opened 2024-09-30 08:15 UTC by PieterCarlu1

2024-09-30 10:43 UTC, slc-peter-vanpoucke requested changes
Best to add the DataMiner version (+ RN) to the new paragraphs

2024-09-30 12:05 UTC, slc-peter-vanpoucke approved these changes

2024-10-01 08:02 UTC, Seppe-Vanhee commented on user-guide/Advanced_Modules/DOM/DOM_objects/DomInstance.md
> +| ValueTooLarge | Attempted to create or update a `DomInstance` with a string value that is too large. The *AssociatedFields* collection contains the IDs of the `SectionDefinition`, `Section` and `Fi
Maybe add the actual limit here as well, so people who search for this error know what the limit is?

2024-10-24 11:04 UTC, MariekeGO approved these changes

2024-10-24 11:04 UTC, merged