Update DCP_change_log.md
SkylineCommunications/dataminer-docs pull request #3787
Opened 2024-10-10 12:34 UTC by KoenAnnys

2024-10-10 13:05 UTC, brayunm requested changes

2024-10-10 13:05 UTC, brayunm commented on release-notes/Cloud/DCP_change_log.md
> +
The following can also be added
```suggestion

#### 10 October 2024 - Enhancement - Catalog - Vendor and Market show in the aside panel

On the detail page of a Connector Catalog item, the vendor and market are no longer displayed as tags but are now visible on the sidepanel.

#### 10 October 2024 - Enhancement - Catalog - Non-authenticated users are able to use "Deploy trial" button

Non-authenticated users are now able to click on the deploy trial button in the header of an item or on a version.
This button will trigger the login and navigate back to the details page in order for them to continue deploying the given item.

```

2024-10-11 06:59 UTC, MariekeGO commented on release-notes/Cloud/DCP_change_log.md
> +#### 10 October 2024 - Enhancement - Catalog - Non-authenticated users are able to use "Deploy trial" button
Do these two RNs also have an intranet ID?

2024-10-11 08:52 UTC, MariekeGO commented on release-notes/Cloud/DCP_change_log.md
> +Using the Catalog API, it is now possible to obtain a Catalog item via its ID (GUID) or original ID using an organization key for authorization.
```suggestion
Using the Catalog API, it is now possible to obtain a Catalog item via its ID using an organization key for authorization.
```

2024-10-11 09:14 UTC, MariekeGO approved these changes

2024-10-11 09:14 UTC, merged