Update Protocol.Params.Param-saveInterval.md
SkylineCommunications/dataminer-docs pull request #3946
Opened 2024-11-20 08:54 UTC by JoaoSE-Skyline

Include details about implementation on tables and columns

2024-11-20 08:55 UTC, JoaoSE-Skyline commented
@SkylineThomasCR

2024-11-20 09:02 UTC, SkylineThomasCR requested changes

2024-11-20 09:02 UTC, SkylineThomasCR commented on develop/schemadoc/Protocol/Protocol.Params.Param-saveInterval.md
> +For column parameters, this is configured by specifying the save option for this column on the table parameter. Additionally, for column parameters, the saveInterval attribute will need to be configu
```suggestion
For column parameters, saving is enabled by configuring the save option for the column within the table parameter. Additionally, the saveInterval attribute must be specified on both the table parameter and the column parameter to ensure proper functionality.
```

2024-11-27 10:19 UTC, MariekeGO approved these changes

2024-11-27 10:19 UTC, merged