Improved info on giving access to cloud features
SkylineCommunications/dataminer-docs pull request #468
Opened 2022-08-29 09:50 UTC by MariekeGO

2022-08-29 13:40 UTC, JordyGit commented
All DataMiner rights/permissions that the linked DataMiner user has are still applied in the web apps. I think there are permissions to access web apps? so these would also still apply.

2022-08-30 06:44 UTC, baptistepa approved these changes

2022-08-30 07:50 UTC, JordyGit requested changes

2022-08-30 07:50 UTC, JordyGit commented on user-guide/Advanced_Modules/Job_Manager/Accessing_the_jobs_app.md
> +If you have been granted [remote access](xref:Controlling_remote_access) to a cloud-connected DataMiner System as a guest, you can connect as follows:
i would remove the 'as a guest' in all the web apps pages, the users need a DCP and DataMiner account so they are not really a guest anymore (?)

```suggestion
If you have been granted [remote access](xref:Controlling_remote_access) to a cloud-connected DataMiner System, you can connect as follows:
```

2022-08-30 07:50 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +After you have registered, you can find the URL on the *Overview* page for the DataMiner System in the Cloud Admin app. The URL is displayed right underneath the name of the connected DataMiner Syste
To be consistent , I think we have used DCP Admin before (and in the UI on https://dataminer.services) 
```suggestion
After you have registered, you can find the URL on the *Overview* page for the DataMiner System in the DCP Admin app. The URL is displayed right underneath the name of the connected DataMiner System. You can also directly navigate to the URL from this section.
```

2022-08-30 07:50 UTC, JordyGit commented on user-guide/Cloud_Platform/CloudAdminApp/Controlling_remote_access.md
> +> Users will only be able to use the remote access feature if they have been given access to cloud features. See [Controlling user access to cloud features](xref:Giving_users_access_to_cloud_features
Isn't this better?
```suggestion
> Users will only be able to use the remote access feature if they have been given access. See [Controlling user access to cloud features](xref:Giving_users_access_to_cloud_features). They will also need to have the [General > DataMiner web apps](xref:DataMiner_user_permissions#general--dataminer-web-apps--dataminer-cube-mobile-access) user permission, as well as any other user permissions required to access specific apps, e.g. [Modules > User-definable apps > View apps](xref:DataMiner_user_permissions#modules--user-definable-apps--view-apps) for the Low-Code Apps.
```

2022-08-30 07:56 UTC, MariekeGO commented on user-guide/Cloud_Platform/CloudAdminApp/DataMiner_Admin_app.md
> +- [Controlling remote access](xref:Controlling_remote_access)
Indeed, that would be another good addition. However, I'd postpone that for a later update, so we can get this one out there as soon as possible.

2022-08-30 09:01 UTC, JordyGit approved these changes

2022-08-30 09:02 UTC, merged