Update Viewing_info_on_deployments.md
SkylineCommunications/dataminer-docs pull request #475
Opened 2022-08-31 09:07 UTC by KevinVerm

Added tip section regarding deployment logging on the dataminer system.

@baptistepa can you also have a look?

2022-08-31 09:10 UTC, baptistepa approved these changes

2022-08-31 10:59 UTC, MariekeGO commented
@baptistepa, I've rephrased the first sentence in the tip. Is this still correct?

2022-09-07 11:49 UTC, baptistepa requested changes
It is not mandatory to install an Artifact Deployer on each DMA, and an Artifact Deployer instance does not need to be next to a DMA at all. As long as it has access to the NATS bus it will be able to work. I would change the wording to something like: "You can find the logging on the server where the Artifact Deployer is installed under the following folder: "

2022-09-07 11:56 UTC, MariekeGO approved these changes

2022-09-07 11:56 UTC, merged