Update Security_Elasticsearch.md
SkylineCommunications/dataminer-docs pull request #617
Opened 2022-10-13 10:25 UTC by daudahabbasi

2022-10-13 10:28 UTC, daudahabbasi commented
Adding @jens-gellynck also for review.

2022-10-13 11:04 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +   Add the following lines to *elasticsearch.yml* file, if you are using `.PEM` certificate generated using `penssl utility` .
Should be 'openssl' utility

2022-10-13 11:05 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +    xpack.security.http.ssl.certificate_authorities: path/to/certificate/authority (if you are using self-signed
maybe add the last part as a comment (prefixed by '#') so the yaml stays valid if someone just copy pastes this

2022-10-13 11:06 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +1. Add the certificates on each Dataminer agent under `Trusted root certification authorities`.
Import the certificate in the 'Trusted Root Certification Authorities' store of the Windows Certificate store.

2022-10-13 11:06 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +    Add the following lines to *elasticsearch.yml* file, if you are using `.PEM` certificate generated using `penssl utility` .
*openssl

2022-10-13 11:06 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +    xpack.security.transport.ssl.certificate_authorities: path/to/certificate/authority (if you are using self-signed
same

2022-10-13 11:07 UTC, jens-gellynck reviewed
Some small feedback

2022-10-17 14:51 UTC, jens-gellynck commented on user-guide/Advanced_Functionality/Security/Advanced_security_configuration/Database_security/Security_Elasticsearch.md
> +    Add the following lines to *elasticsearch.yml* file, if you are using `.PEM` certificate generated using `penssl` utility.
openssl?

2022-10-17 14:51 UTC, jens-gellynck requested changes
replace penssl with 'openssl'

2022-10-20 09:25 UTC, MariekeGO commented
@jens-gellynck I've made a few more small changes. Could you confirm if this is now OK to merge?

2022-10-26 06:25 UTC, jens-gellynck approved these changes
LGTM

2022-10-26 06:33 UTC, MariekeGO approved these changes

2022-10-26 06:33 UTC, merged