RN 34857
SkylineCommunications/dataminer-docs pull request #757
Opened 2022-11-29 13:10 UTC by EdithLansens

2022-11-29 13:57 UTC, HansSolos requested changes

2022-11-29 13:57 UTC, HansSolos commented on release-notes/Cube/Cube_Feature_Release_10.3/Cube_10.3.1.md
> +The number of resources shown on a timeline is limited to 100 resources to avoid delay while loading the bands.
There is no software limit of 100 resources.
Better would be to say that is recommended to use a filter which results in less than 100 resources.

2022-11-29 13:57 UTC, HansSolos commented on user-guide/Basic_Functionality/Visio/SRM/Embedding_a_Resource_Manager_component.md
> +> The number of resources shown on a timeline is limited to 100 resources to avoid delay while loading the bands.
As stated above, the warning in the RN is not a software limit, but a warning to the user for using the filter wisely.

2022-11-29 13:57 UTC, HansSolos commented on user-guide/Basic_Functionality/Visio/SRM/Embedding_a_Resource_Manager_component.md
> +From DataMiner 10.3.1/10.4.0 onwards, you can pass exposers by object ID.
should change to "you can pass resource exposer as a filter"

2022-11-29 13:57 UTC, HansSolos commented on user-guide/Basic_Functionality/Visio/SRM/Embedding_a_Resource_Manager_component.md
> +
I would add quite some examples, as stated in internal comments in the RN.

2022-11-30 10:16 UTC, EdithLansens commented
Could you take another look, @HansSolos? Thanks!

2022-11-30 10:35 UTC, HansSolos requested changes

2022-11-30 10:35 UTC, HansSolos commented on user-guide/Basic_Functionality/Visio/SRM/Embedding_a_Resource_Manager_component.md
> +> The server side filter is case sensitive with regard to profile parameter keys.
Could you also add that it is expected that the profile parameter keys are represented with the number format.
Example:
- {d248b04f-2253-41c6-a92a-e12768fe2b20} is incorrect, this is format B (braces)
- (d248b04f-2253-41c6-a92a-e12768fe2b20) is incorrect, this is format P (parentheses)
- d248b04f-2253-41c6-a92a-e12768fe2b20 is correct, this is format D (default)
- d248b04f225341c6a92ae12768fe2b20 is correct, this is format N (number)

more info: https://learn.microsoft.com/en-us/dotnet/api/system.guid.tostring?view=netframework-4.8

2022-11-30 14:13 UTC, HansSolos approved these changes

2022-12-06 11:55 UTC, merged