SRM addition
SkylineCommunications/dataminer-docs pull request #921
Opened 2023-01-18 13:45 UTC by MariekeGO

Includes:
- SRM logging + logging configuration
- Configuration of SRM alarm monitoring
- Configuration of custom booking blocks + booking list columns
- Advanced service orchestration configuration for bookings, custom events, booking life cycle states, profile instances, resources, service definitions, and service profiles
- A multitude of small additions and improvements

2023-02-02 13:14 UTC, edalslc requested changes

2023-02-06 13:21 UTC, MariekeGO commented on user-guide/Advanced_Modules/SRM/The_Services_module/SRM_Services_profiles.md
> +    > Only regular service definitions can be selected, not service definition templates.
I based this note on behavior I encountered in our test setup, but possibly this was a bug then. I'll remove it again.

2023-02-06 13:40 UTC, MariekeGO commented
@edalslc, I've implemented the necessary changes based on your feedback. Could you take a look?

2023-03-03 08:56 UTC, edalslc approved these changes

2023-03-03 08:58 UTC, merged